package net.yacy.scoutro.api;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Assert;
import org.junit.Test;

import net.yacy.scoutro.agents.Agent;
import net.yacy.scoutro.agents.AgentActionRegistry;

/**
 * The published action catalog (generated by tools/scoutro/generate_api_description.py)
 * must describe exactly the grants of AgentActionRegistry.
 */
public class AgentCatalogTest {

    private static JSONObject catalog() throws Exception {
        return new JSONObject(new String(Files.readAllBytes(new File("htroot/env/scoutro/api/actions.json").toPath()),
                StandardCharsets.UTF_8));
    }

    @Test
    public void grantsMatchTheRegistry() throws Exception {
        final JSONArray grants = catalog().getJSONObject("agentAccess").getJSONArray("grants");
        final List<String> published = new ArrayList<>();
        for (int i = 0; i < grants.length(); i++) {
            final JSONObject g = grants.getJSONObject(i);
            final String id = g.getString("name");
            published.add(id);
            final AgentActionRegistry.Action a = AgentActionRegistry.get(id);
            Assert.assertNotNull("unknown grant in the catalog: " + id, a);
            Assert.assertEquals(id, a.risk.id, g.getString("risk"));
            Assert.assertEquals(id, a.scoped, g.getBoolean("scoped"));
            Assert.assertEquals(id, a.presetable, g.getBoolean("presetable"));
            final Set<String> kinds = new LinkedHashSet<>();
            for (final Agent.Kind k : a.kinds) {
                kinds.add(k.id);
            }
            final Set<String> pubKinds = new LinkedHashSet<>();
            for (int k = 0; k < g.getJSONArray("kinds").length(); k++) {
                pubKinds.add(g.getJSONArray("kinds").getString(k));
            }
            Assert.assertEquals(id, kinds, pubKinds);
            final JSONObject http = g.getJSONObject("http");
            Assert.assertEquals(id, a.method, http.getString("method"));
            Assert.assertEquals(id, AgentActionRegistry.BASE_PATH + a.path.replaceAll("\\?.*$", ""), http.getString("path"));
            for (final String preset : AgentActionRegistry.presetNames()) {
                final boolean inPreset = AgentActionRegistry.preset(preset).contains(id);
                boolean published2 = false;
                for (int p = 0; p < g.getJSONArray("presets").length(); p++) {
                    published2 |= preset.equals(g.getJSONArray("presets").getString(p));
                }
                Assert.assertEquals(id + " in " + preset, inPreset, published2);
            }
        }
        final List<String> registry = new ArrayList<>();
        for (final AgentActionRegistry.Action a : AgentActionRegistry.all()) {
            registry.add(a.id);
        }
        Assert.assertEquals(registry, published);
    }

    @Test
    public void everyRoutedAgentPathIsDescribed() throws Exception {
        final JSONObject openapi = new JSONObject(new String(Files.readAllBytes(
                new File("htroot/env/scoutro/api/openapi.json").toPath()), StandardCharsets.UTF_8));
        final JSONObject paths = openapi.getJSONObject("paths");
        final String[][] routes = {
            {"GET", "capabilities"}, {"POST", "heartbeat"}, {"GET", "search"}, {"GET", "index"},
            {"GET", "index/lookup"}, {"GET", "index/evidence"}, {"GET", "crawls"}, {"POST", "crawls"},
            {"GET", "seo/hosts"}, {"GET", "seo/hosts/{host}"}, {"GET", "seo/hosts/{host}/pages"}, {"GET", "seo/pages/{id}"},
            {"GET", "crawls/{id}"}, {"POST", "crawls/{id}/stop"}, {"GET", "system"}, {"GET", "config"}, {"PATCH", "config"}};
        for (final String[] r : routes) {
            final List<String> segs = new ArrayList<>();
            for (final String s : r[1].split("/")) {
                segs.add(s.replace("{id}", "c1"));
            }
            Assert.assertNotNull("routed: " + r[1], AgentApi.route(r[0], segs).action);
            final JSONObject p = paths.optJSONObject("/agent/v1/" + r[1]);
            Assert.assertNotNull("described: " + r[1], p);
            Assert.assertNotNull(r[0] + " " + r[1], p.optJSONObject(r[0].toLowerCase()));
        }
        Assert.assertNotNull(openapi.getJSONObject("components").getJSONObject("securitySchemes").optJSONObject("agentBearer"));
    }
}
