package net.yacy.scoutro.api;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

import org.json.JSONArray;
import org.json.JSONObject;
import org.junit.Assert;
import org.junit.Test;

import net.yacy.scoutro.agents.Agent;
import net.yacy.scoutro.agents.AgentActionRegistry;

/**
 * The published action catalog (generated by tools/scoutro/generate_api_description.py)
 * must describe exactly the grants of AgentActionRegistry.
 */
public class AgentCatalogTest {

    private static JSONObject catalog() throws Exception {
        return new JSONObject(new String(Files.readAllBytes(new File("htroot/env/scoutro/api/actions.json").toPath()),
                StandardCharsets.UTF_8));
    }

    @Test
    public void grantsMatchTheRegistry() throws Exception {
        final JSONArray grants = catalog().getJSONObject("agentAccess").getJSONArray("grants");
        final List<String> published = new ArrayList<>();
        for (int i = 0; i < grants.length(); i++) {
            final JSONObject g = grants.getJSONObject(i);
            final String id = g.getString("name");
            published.add(id);
            final AgentActionRegistry.Action a = AgentActionRegistry.get(id);
            Assert.assertNotNull("unknown grant in the catalog: " + id, a);
            Assert.assertEquals(id, a.risk.id, g.getString("risk"));
            Assert.assertEquals(id, a.scoped, g.getBoolean("scoped"));
            Assert.assertEquals(id, a.presetable, g.getBoolean("presetable"));
            final Set<String> kinds = new LinkedHashSet<>();
            for (final Agent.Kind k : a.kinds) {
                kinds.add(k.id);
            }
            final Set<String> pubKinds = new LinkedHashSet<>();
            for (int k = 0; k < g.getJSONArray("kinds").length(); k++) {
                pubKinds.add(g.getJSONArray("kinds").getString(k));
            }
            Assert.assertEquals(id, kinds, pubKinds);
            final JSONObject http = g.getJSONObject("http");
            Assert.assertEquals(id, a.method, http.getString("method"));
            Assert.assertEquals(id, AgentActionRegistry.BASE_PATH + a.path.replaceAll("\\?.*$", ""), http.getString("path"));
            for (final String preset : AgentActionRegistry.presetNames()) {
                final boolean inPreset = AgentActionRegistry.preset(preset).contains(id);
                boolean published2 = false;
                for (int p = 0; p < g.getJSONArray("presets").length(); p++) {
                    published2 |= preset.equals(g.getJSONArray("presets").getString(p));
                }
                Assert.assertEquals(id + " in " + preset, inPreset, published2);
            }
        }
        final List<String> registry = new ArrayList<>();
        for (final AgentActionRegistry.Action a : AgentActionRegistry.all()) {
            registry.add(a.id);
        }
        Assert.assertEquals(registry, published);
    }

    @Test
    public void everyRoutedAgentPathIsDescribed() throws Exception {
        final JSONObject openapi = new JSONObject(new String(Files.readAllBytes(
                new File("htroot/env/scoutro/api/openapi.json").toPath()), StandardCharsets.UTF_8));
        final JSONObject paths = openapi.getJSONObject("paths");
        final String[][] routes = {
            {"GET", "capabilities"}, {"POST", "heartbeat"}, {"GET", "search"}, {"GET", "index"},
            {"GET", "index/lookup"}, {"GET", "index/evidence"}, {"GET", "crawls"}, {"POST", "crawls"},
            {"GET", "seo/hosts"}, {"GET", "seo/hosts/{host}"}, {"GET", "seo/hosts/{host}/pages"}, {"GET", "seo/pages/{id}"},
            {"GET", "reports/jobs"}, {"GET", "reports/jobs/{id}"}, {"GET", "reports/collections/{collection}"},
            {"GET", "reports/collections/{collection}/hosts"}, {"GET", "reports/hosts/{host}"},
            {"GET", "crawls/{id}"}, {"POST", "crawls/{id}/stop"}, {"GET", "system"}, {"GET", "config"}, {"PATCH", "config"},
            {"GET", "kg/entities"}, {"GET", "kg/entities/{id}"}, {"GET", "kg/entities/{id}/statements"}, {"GET", "kg/statements/{id}"},
            {"GET", "kg/statements/{id}/evidence"}, {"GET", "kg/hosts/{host}/entities"}, {"GET", "kg/sources/{docId}"},
            {"GET", "kg/export"}, {"GET", "kg/changes"}};
        for (final String[] r : routes) {
            final List<String> segs = new ArrayList<>();
            for (final String s : r[1].split("/")) {
                segs.add(s.replace("{id}", "c1"));
            }
            Assert.assertNotNull("routed: " + r[1], AgentApi.route(r[0], segs).action);
            final JSONObject p = paths.optJSONObject("/agent/v1/" + r[1]);
            Assert.assertNotNull("described: " + r[1], p);
            Assert.assertNotNull(r[0] + " " + r[1], p.optJSONObject(r[0].toLowerCase()));
        }
        Assert.assertNotNull(openapi.getJSONObject("components").getJSONObject("securitySchemes").optJSONObject("agentBearer"));
        // the administrator routes of the knowledge graph are neither routed nor described on the agent path
        for (final String admin : new String[] {"kg/status", "kg/control", "kg/export/download"}) {
            Assert.assertNull(admin, AgentApi.route("GET", java.util.Arrays.asList(admin.split("/"))).action);
            Assert.assertNull(admin, paths.optJSONObject("/agent/v1/" + admin));
        }
    }

    @Test
    public void knowledgeGraphActionsNameTheirGrant() throws Exception {
        final JSONArray actions = catalog().getJSONArray("actions");
        int read = 0;
        int export = 0;
        for (int i = 0; i < actions.length(); i++) {
            final JSONObject a = actions.getJSONObject(i);
            final String name = a.getString("name");
            if (!name.startsWith("kg.")) {
                continue;
            }
            final JSONObject agent = a.getJSONObject("agent");
            final java.util.Set<String> reads = java.util.Set.of("kg.entities", "kg.entity", "kg.entity.statements", "kg.statement",
                    "kg.statement.evidence", "kg.host.entities", "kg.source",
                    // vocabulary 2 (package 6)
                    "kg.entity.business", "kg.entity.neighborhood", "kg.compare", "kg.derived", "kg.facets",
                    // services of the same name across providers (package 6.1)
                    "kg.services", "kg.services.providers");
            if (!reads.contains(name) && !name.equals("kg.export") && !name.equals("kg.changes")) {
                // status, control, the download, backups and every later administrator route: never an agent grant
                Assert.assertFalse(name, agent.getBoolean("grantable"));
                continue;
            }
            final String grant = name.equals("kg.export") || name.equals("kg.changes") ? "kg.export" : "kg.read";
            Assert.assertEquals(name, grant, agent.getString("grant"));
            Assert.assertEquals(name, "GET", agent.getJSONObject("http").getString("method"));
            Assert.assertTrue(name, agent.getJSONObject("http").getString("path").startsWith("/scoutro/api/agent/v1/kg/"));
            final java.util.List<String> segs = java.util.Arrays.asList(agent.getJSONObject("http").getString("path")
                    .substring("/scoutro/api/agent/v1/".length()).split("/"));
            Assert.assertEquals(name, grant, AgentApi.route("GET", segs).action);
            if (grant.equals("kg.read")) read++; else export++;
        }
        Assert.assertEquals(12, read);
        Assert.assertEquals(2, export);
    }
}
